In [1]:
import tensorflow as tf
from tensorflow.python.ops import rnn_cell
import numpy as np
from nltk import pos_tag, ne_chunk, FreqDist
from nltk.chunk import tree2conlltags
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
import time

from pycorenlp import StanfordCoreNLP
import pickle

In [2]:
# a = tf.constant(np.arange(0, 30, dtype=np.int32), shape=[2, 5, 3])
# b = tf.constant(np.arange(0, 24, dtype=np.int32), shape=[2, 3, 4])
# c = tf.matmul(a, b)
# c

In [3]:
# sess = tf.Session()
# print(sess.run(a[0]))
# print('~~~~~~~~')
# print(sess.run(b[0]))
# print('~~~~~~~~')
# print(sess.run(c))
# sess.close()

In [4]:
# x = tf.constant(np.arange(0, 30, dtype=np.float),shape=[2, 5, 3])
# x2 = tf.nn.softmax(x,axis=2)

# sess = tf.Session()
# print(sess.run(x[0]))
# print('~~~~~~~~')
# print(sess.run(x2[0]))
# print('~~~~~~~~')
# print(np.sum(sess.run(x2[0]),axis=1))
# sess.close()

In [5]:
# y = tf.constant(np.arange(0, 10, dtype=np.float), shape=[2, 5, 1])
# z = tf.constant(np.arange(0, 15, dtype=np.float), shape=[1, 5, 3])
# w = tf.multiply(y,z)

# sess = tf.Session()
# print(sess.run(y))
# print('~~~~~~~~')
# print(sess.run(z))
# print('~~~~~~~~')
# print(sess.run(w))
# sess.close()

In [6]:
# a = np.random.permutation(24).reshape(2,3,4)
# print(a[0])
# print(a[1])

In [7]:
# idx = np.transpose(np.asarray([np.unravel_index(np.argmax(x, axis=None), x.shape) for x in a]))
# print(idx)
# row_max = idx[0]
# col_max = idx[1]

In [8]:
# h = 100
# rnn_cell_fw = [rnn_cell.GRUCell(h) for _ in range(3)]
# rnn_cell_fw

In [9]:
# pos2int = {"CC":0, "CD":1, "DT":2, "EX":3, "FW":4, "IN":5, "JJ":6, "JJR":7, "JJS":8, \
# "LS":9, "MD":10, "NN":11, "NNS":12, "NNP":13, "NNPS":14, "PDT":15, "POS":16, \
# "PRP":17, "PRP$":18, "RB":19, "RBR":20, "RBS":21, "RP":22, "SYM":23, "TO":24, \
# "UH":25, "VB":26, "VBD":27, "VBG":28, "VBN":29, "VBP":30, "VBZ":31, "WDT":32, \
# "WP":33, "WP$":34, "WRB":35}

# ner2int_simple = {"":0,"FACILITY":1, "GPE":2, "GSP":3, "LOCATION":4, "ORGANIZATION":5, "PERSON":6}

# s = "Nancy Smith went to the United States last year and attended McDonalds at 3 o'clock"
# #s = "bskyb launched its hdtv service , sky+ hd , on 22 may 2006 . prior to its launch , bskyb claimed that 40,000 people had registered to receive the hd service "

# s = s.split()

# print(ne_chunk(pos_tag(s)))
# print

# pos = [pos2int[x[1]] for x in pos_tag(s)]
# print(pos)

# ner = [ner2int_simple[str(x[2])[2:]] for x in tree2conlltags(ne_chunk(pos_tag(s)))]
# print(ner)

In [10]:
# import re
# def split_by_whitespace(sentence):
#     words = []
#     for space_separated_fragment in sentence.strip().split():
#         words.extend(re.split(" ", space_separated_fragment))
#     return [w for w in words if w]

# def sentence_to_token_ids(sentence):
#     """Turns an already-tokenized sentence string into word indices
#     e.g. "i do n't know" -> [9, 32, 16, 96]
#     Note any token that isn't in the word2id mapping gets mapped to the id for UNK
#     """
#     tokens = split_by_whitespace(sentence) # list of strings
#     return tokens

In [11]:
context_line = "the service started on 1 september 1993 based on the idea from the then chief executive officer , sam chisholm and rupert murdoch , of converting the company business strategy to an entirely fee-based concept . the new package included four channels formerly available free-to-air , broadcasting on astra 's satellites , as well as introducing new channels . the service continued until the closure of bskyb 's analogue service on 27 september 2001 , due to the launch and expansion of the sky digital platform . some of the channels did broadcast either in the clear or soft encrypted ( whereby a videocrypt decoder was required to decode , without a subscription card ) prior to their addition to the sky multichannels package . within two months of the launch , bskyb gained 400,000 new subscribers , with the majority taking at least one premium channel as well , which helped bskyb reach 3.5 million households by mid-1994 . michael grade criticized the operations in front of the select committee on national heritage , mainly for the lack of original programming on many of the new channels ."

In [12]:
# nlp = StanfordCoreNLP('http://localhost:9000')
# context_tokens = sentence_to_token_ids(context_line)

# pos2int = {"CC":0, "CD":1, "DT":2, "EX":3, "FW":4, "IN":5, "JJ":6, "JJR":7, "JJS":8, \
#     "LS":9, "MD":10, "NN":11, "NNS":12, "NNP":13, "NNPS":14, "PDT":15, "POS":16, \
#     "PRP":17, "PRP$":18, "RB":19, "RBR":20, "RBS":21, "RP":22, "SYM":23, "TO":24, \
#     "UH":25, "VB":26, "VBD":27, "VBG":28, "VBN":29, "VBP":30, "VBZ":31, "WDT":32, \
#     "WP":33, "WP$":34, "WRB":35}

# ner2int = {"O":0, "PERSON":1, "LOCATION":2, "ORGANIZATION":3, "MISC":4, "MONEY":5, \
#            "NUMBER":6, "ORDINAL":7, "PERCENT":8, "DATE":9, "TIME":10, "DURATION":11, "SET":12, \
#            "EMAIL":13, "URL":14, "CITY":15, "STATE_OR_PROVINCE":16, "COUNTRY":17, "NATIONALITY":18, \
#            "RELIGION":19, "TITLE":20, "IDEOLOGY":21, "CRIMINAL_CHARGE":22, "CAUSE_OF_DEATH":23}

# output = nlp.annotate(context_line, properties={
#     'annotators': 'pos,ner',
#     'tokenize.language': 'Whitespace',
#     'outputFormat': 'json'})
# ner_tags = np.array([ner2int[str(tok['ner'])] if str(tok['ner']) in ner2int.keys() else 0 for s in output['sentences'] for tok in s['tokens']])
# pos_tags = np.array([pos2int[str(tok['pos'])] if str(tok['pos']) in pos2int.keys() else -1 for s in output['sentences'] for tok in s['tokens']])
# lems     = [tok['lemma'] for s in output['sentences'] for tok in s['tokens']]
# assert (len(ner_tags)==len(context_tokens)), "%d, %d, %s" % (len(ner_tags), len(context_tokens), context_line)
# assert (len(pos_tags)==len(context_tokens)), "%d, %d" % (len(pos_tags), len(context_tokens))
# assert (len(lems)==len(context_tokens)),     "%d, %d" % (len(lems),     len(context_tokens))


# print(context_line)
# print(ner_tags)
# print(pos_tags)
# print(len(ner_tags))
# print(len(pos_tags))
# print(len(sentence_to_token_ids(context_line)))

In [23]:
context_tokens = ['this','is','a','bart']
lems           = ['this','is','a','bar']
qn_tokens  = ['foo','bar','this','this','a']

match_orig  = [int(sum([context_token==q for q in qn_tokens])==1)     for context_token     in context_tokens] # original form
match_lemma = [int(sum([context_token_lem==q for q in qn_tokens])==1) for context_token_lem in lems]    # lemma form

print(match_orig)
print(match_lemma)

# f = np.concatenate([np.expand_dims(x,1) for x in (a,b,c)],axis=1)
# f

[0, 0, 1, 0]
[0, 0, 1, 1]


In [22]:
context_token = context_tokens[0]
int(sum([context_token==q for q in qn_tokens])==1)

0

In [14]:
# def get_wordnet_pos(treebank_tag):

#     if treebank_tag.startswith('J'):
#         return wordnet.ADJ
#     elif treebank_tag.startswith('V'):
#         return wordnet.VERB
#     elif treebank_tag.startswith('N'):
#         return wordnet.NOUN
#     elif treebank_tag.startswith('R'):
#         return wordnet.ADV
#     else:
#         return ''

In [15]:
# context_tokens = split_by_whitespace(context_line)
# pos_tree = pos_tag(context_tokens)
# ne_tree = ne_chunk(pos_tree)
# tree2conlltags(ne_tree)

# pos2int = {"CC":0, "CD":1, "DT":2, "EX":3, "FW":4, "IN":5, "JJ":6, "JJR":7, "JJS":8, \
#     "LS":9, "MD":10, "NN":11, "NNS":12, "NNP":13, "NNPS":14, "PDT":15, "POS":16, \
#     "PRP":17, "PRP$":18, "RB":19, "RBR":20, "RBS":21, "RP":22, "SYM":23, "TO":24, \
#     "UH":25, "VB":26, "VBD":27, "VBG":28, "VBN":29, "VBP":30, "VBZ":31, "WDT":32, \
#     "WP":33, "WP$":34, "WRB":35}

# ner2int = {"O":0, "PERSON":1, "LOCATION":2, "ORGANIZATION":3, "GSP":4, "GPE":5, "FACILITY":6}

# pos_keys = pos2int.keys()
# ner_keys = ner2int.keys() 

# pos_tags = [p[1] for p in pos_tag(context_tokens)]
# ner_tags = [ne[2][2:] for ne in tree2conlltags(ne_chunk(pos_tree))]

# pos_ids = [pos2int[pos] if pos in pos_keys else -1 for pos in pos_tags]
# ner_ids = [ner2int[ne]  if ne  in ner_keys else 0  for ne  in ner_tags]
            
# lemmatizer = WordNetLemmatizer()
# lems = [str(lemmatizer.lemmatize(tok,get_wordnet_pos(pos))) if get_wordnet_pos(pos) else str(lemmatizer.lemmatize(tok)) for tok,pos in zip(context_tokens,pos_tags)]

# print(ner_ids)
# print(pos_tags)
# print(lems)

# print(len(ner_ids))
# print(len(pos_ids))
# print(len(lems))
# print

In [16]:
# from nltk.tag import StanfordNERTagger
# import time

# st = StanfordNERTagger('/Users/andrewweitz/_Stanford/year6/cs224n/stanford-ner-2018-02-27/classifiers/english.all.3class.distsim.crf.ser.gz',
#     '/Users/andrewweitz/_Stanford/year6/cs224n/stanford-ner-2018-02-27/stanford-ner.jar',
#     encoding='utf-8')

# tic = time.time()
# classified_text = st.tag(context_tokens)
# print(time.time()-tic)
# print(classified_text)

In [17]:
# from sner import Ner

# tagger = Ner(host='localhost',port=9199)

# tic = time.time()
# t = tagger.get_entities(context_line)
# print(time.time()-tic)

In [18]:
# import nltk
# from nltk.tag.perceptron import PerceptronTagger
# tagger = PerceptronTagger()
# tagset = None
# tic = time.time()
# tags = nltk.tag._pos_tag(context_tokens, tagset, tagger)
# print(time.time()-tic)
# tags

In [19]:
# x = pickle.load( open( "../output.p", "rb" ) )

# from vocab import PAD_ID, UNK_ID
# def padded2(token_batch, num_feats, batch_pad=0, ):
#     """
#     Inputs:
#       token_batch: List (length batch size) of arrays.
#       batch_pad: Int. Length to pad to. If 0, pad to maximum length sequence in token_batch.
#     Returns:
#       List (length batch_size) of padded of lists of ints.
#         All are same length - batch_pad if batch_pad!=0, otherwise the maximum length in token_batch
#     """
#     maxlen = max(map(lambda x: len(x), token_batch)) if batch_pad == 0 else batch_pad
#     return map(lambda token_list: token_list + [num_feats*[PAD_ID,]] * (maxlen - len(token_list)) , token_batch)

# tic = time.time()
# z = padded2(x,4,600)
# print(time.time()-tic)

# y = np.array(z)
# y.shape

# f = x[0]
# print(len(f))
# f = f[:130]
# print(len(f))


In [20]:
# a = 0.4
# tic = time.time()
# fdist = FreqDist(context_tokens)
# tf = [a + (1-a)*fdist[w]/float(max(fdist.values())) for w in context_tokens]
# print(time.time()-tic)

In [21]:
# char2id = {"a":2, "b":3, "c":4, "d":5, "e":6, "f":7, "g":8, \
#     "h":9, "i":10, "j":11, "k":12, "l":13, "m":14, "n":15, "o":16, \
#     "p":17, "q":18, "r":19, "s":20, "t":21, "u":22, "v":23, "w":24, \
#     "x":25, "y":26, "z":27, "0":28, "1":29, "2":30, "3":31, "4":32, \
#     "5":33, "6":34, "7":35, "8":36, "9":37, ".":38, ",":39, '"':40, \
#     "?":41, "'":42}
    
# tokens = ["This","is","a","WORD2?foo"]

In [22]:
# word_len = 8
# context_len = 15

# tic = time.time()
# charIDs = [[char2id[char] if char in char2id.keys() else -1 for char in tok.lower()] for tok  in tokens ]
# print(time.time()-tic)

# tic = time.time()
# charIDs = [[ord(char) for char in tok.lower()] for tok  in tokens ]
# print(time.time()-tic)

# charIDs = [x[:word_len] for x in charIDs] # truncate to word_len
# charIDs = padded(charIDs,word_len)
# charIDs

In [23]:
# PAD_ID = 0
# UNK_ID = 1
# def padded(token_batch, batch_pad=0):
#     maxlen = max(map(lambda x: len(x), token_batch)) if batch_pad == 0 else batch_pad
#     return map(lambda token_list: token_list + [PAD_ID] * (maxlen - len(token_list)), token_batch)

In [24]:
# char_ids = pickle.load( open( "../char_ids.p", "rb" ) )

In [25]:
qn_ids = [[1,29,42,20,64,100,42,399],[400,33,3,33,42,10,10,399]]
mcids = [29, 42, 400]
mcids_dict = dict(zip(mcids,range(len(mcids))))

In [26]:
mask = [[x in mcids_dict.keys() for x in qn_id ] for qn_id in qn_ids]
emb_indices =  [[mcids_dict.get(x,0) for x in qn_id] for qn_id in qn_ids]

print(mask)
print(emb_indices)

[[False, True, True, False, False, False, True, False], [True, False, False, False, True, False, False, False]]
[[0, 0, 1, 0, 0, 0, 1, 0], [2, 0, 0, 0, 1, 0, 0, 0]]


In [7]:
emb         = tf.constant([[[-1,-2,-3], [-4,-5,-6]], [[1,2,3], [4,5,6]]])
emb_common  = tf.constant([[[-10,-20,-30], [-40,-50,-60]], [[10,20,30], [40,50,60]]])

npmask = np.array([[1,0],[0,1]])
mask = tf.constant(npmask,dtype=tf.bool)

mask = tf.reshape(mask,[-1,])
emb  = tf.reshape(emb,[-1,3])
emb_common = tf.reshape(emb_common,[-1,3])

print(mask.get_shape())
print(emb.get_shape())
print(emb_common.get_shape())

output = tf.where(mask,emb_common,emb)
print(output.get_shape())
output = tf.reshape(output,[-1,2,3])
print(output.get_shape())

sess = tf.Session()
print(sess.run(output))
sess.close()

(4,)
(4, 3)
(4, 3)
(4, 3)
(2, 2, 3)
[[[-10 -20 -30]
  [ -4  -5  -6]]

 [[  1   2   3]
  [ 40  50  60]]]


In [8]:
x = [False,True,False]
np.array(x)

array([False,  True, False])

In [8]:
a  = tf.constant([[11,22,33],[1,0,1],[4,4,4],[-1,2,5]])
b  = tf.gather(a,[1,3])

sess = tf.Session()
print(sess.run(b))
sess.close()

[[ 1  0  1]
 [-1  2  5]]
