In [2]:
import tensorflow as tf
from tensorflow.python.ops import rnn_cell
import numpy as np

In [11]:
a = tf.constant(np.arange(0, 30, dtype=np.int32), shape=[2, 5, 3])
b = tf.constant(np.arange(0, 24, dtype=np.int32), shape=[2, 3, 4])
c = tf.matmul(a, b)
c

<tf.Tensor 'MatMul_2:0' shape=(2, 5, 4) dtype=int32>

In [12]:
sess = tf.Session()
print(sess.run(a[0]))
print('~~~~~~~~')
print(sess.run(b[0]))
print('~~~~~~~~')
print(sess.run(c))
sess.close()

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
~~~~
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
~~~~
[[[  20   23   26   29]
  [  56   68   80   92]
  [  92  113  134  155]
  [ 128  158  188  218]
  [ 164  203  242  281]]

 [[ 776  824  872  920]
  [ 920  977 1034 1091]
  [1064 1130 1196 1262]
  [1208 1283 1358 1433]
  [1352 1436 1520 1604]]]


In [19]:
x = tf.constant(np.arange(0, 30, dtype=np.float),shape=[2, 5, 3])
x2 = tf.nn.softmax(x,axis=2)

sess = tf.Session()
print(sess.run(x[0]))
print('~~~~~~~~')
print(sess.run(x2[0]))
print('~~~~~~~~')
print(np.sum(sess.run(x2[0]),axis=1))
sess.close()

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]]
~~~~~~~~
[[0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]]
~~~~~~~~
[1. 1. 1. 1. 1.]


In [28]:
y = tf.constant(np.arange(0, 10, dtype=np.float), shape=[2, 5, 1])
z = tf.constant(np.arange(0, 15, dtype=np.float), shape=[1, 5, 3])
w = tf.multiply(y,z)

sess = tf.Session()
print(sess.run(y))
print('~~~~~~~~')
print(sess.run(z))
print('~~~~~~~~')
print(sess.run(w))
sess.close()

[[[0.]
  [1.]
  [2.]
  [3.]
  [4.]]

 [[5.]
  [6.]
  [7.]
  [8.]
  [9.]]]
~~~~~~~~
[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]
  [ 9. 10. 11.]
  [12. 13. 14.]]]
~~~~~~~~
[[[  0.   0.   0.]
  [  3.   4.   5.]
  [ 12.  14.  16.]
  [ 27.  30.  33.]
  [ 48.  52.  56.]]

 [[  0.   5.  10.]
  [ 18.  24.  30.]
  [ 42.  49.  56.]
  [ 72.  80.  88.]
  [108. 117. 126.]]]


In [2]:
a = np.random.permutation(24).reshape(2,3,4)
print(a[0])
print(a[1])

[[16  7  1 12]
 [ 3  5  8 23]
 [ 2  0 20  6]]
[[22 18  9 15]
 [21 17 13 19]
 [11 10 14  4]]


In [4]:
idx = np.transpose(np.asarray([np.unravel_index(np.argmax(x, axis=None), x.shape) for x in a]))
print(idx)
row_max = idx[0]
col_max = idx[1]

[[1 0]
 [3 0]]


In [11]:
h = 100
rnn_cell_fw = [rnn_cell.GRUCell(h) for _ in range(3)]
rnn_cell_fw